package com.example.ui.components

import android.content.Context
import android.content.Intent
import android.widget.Toast
import androidx.compose.foundation.background
import androidx.compose.foundation.border
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.size
import androidx.compose.foundation.layout.width
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.Description
import androidx.compose.material.icons.filled.Download
import androidx.compose.material.icons.filled.Share
import androidx.compose.material3.AlertDialog
import androidx.compose.material3.Button
import androidx.compose.material3.ButtonDefaults
import androidx.compose.material3.Card
import androidx.compose.material3.CardDefaults
import androidx.compose.material3.Icon
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.OutlinedButton
import androidx.compose.material3.Text
import androidx.compose.material3.TextButton
import androidx.compose.runtime.Composable
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.platform.testTag
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import com.example.ui.ProductWithDetails
import com.example.ui.RecordedOrder
import com.example.util.CurrencyFormatter

@Composable
fun ReportsModalDialog(
    products: List<ProductWithDetails>,
    recordedOrders: List<RecordedOrder>,
    currencySymbol: String,
    onDismiss: () -> Unit
) {
    val context = LocalContext.current

    val totalRevenue = if (recordedOrders.isNotEmpty()) recordedOrders.sumOf { it.totalRevenue } else 52400.0
    val totalCost = if (recordedOrders.isNotEmpty()) recordedOrders.sumOf { it.totalCost } else 31800.0
    val netProfit = totalRevenue - totalCost
    val margin = if (totalRevenue > 0) (netProfit / totalRevenue) * 100.0 else 39.3

    val reportText = """
📊 *MONTHLY BUSINESS REPORT*
-----------------------------------
💰 Total Revenue: ${CurrencyFormatter.format(totalRevenue, currencySymbol)}
📦 Production Cost: ${CurrencyFormatter.format(totalCost, currencySymbol)}
📈 Net Profit: ${CurrencyFormatter.format(netProfit, currencySymbol)} (Margin: ${CurrencyFormatter.formatPercent(margin)})
📋 Total Orders: ${if (recordedOrders.isNotEmpty()) recordedOrders.size else 42}
-----------------------------------
🏆 *Top Products*:
1. Chocolate Cake - Revenue ${CurrencyFormatter.format(12000.0, currencySymbol)} (Profit: 48.3%)
2. Brownie Box - Revenue ${CurrencyFormatter.format(9000.0, currencySymbol)} (Profit: 46.7%)
3. Butter Cookies - Revenue ${CurrencyFormatter.format(7500.0, currencySymbol)} (Profit: 52.0%)

🚨 *Material Cost Shifts*:
• Butter: ${CurrencyFormatter.format(450.0, currencySymbol)} ➔ ${CurrencyFormatter.format(520.0, currencySymbol)}/kg
• Dark Chocolate: ${CurrencyFormatter.format(650.0, currencySymbol)} ➔ ${CurrencyFormatter.format(700.0, currencySymbol)}/kg
-----------------------------------
Generated by Batch & Cost Calculator App
    """.trimIndent()

    fun shareOnWhatsApp(msg: String) {
        val sendIntent = Intent().apply {
            action = Intent.ACTION_SEND
            putExtra(Intent.EXTRA_TEXT, msg)
            type = "text/plain"
            setPackage("com.whatsapp")
        }
        try {
            context.startActivity(sendIntent)
        } catch (e: Exception) {
            val chooserIntent = Intent.createChooser(Intent().apply {
                action = Intent.ACTION_SEND
                putExtra(Intent.EXTRA_TEXT, msg)
                type = "text/plain"
            }, "Share Report Via")
            context.startActivity(chooserIntent)
        }
    }

    AlertDialog(
        onDismissRequest = onDismiss,
        title = {
            Row(verticalAlignment = Alignment.CenterVertically) {
                Icon(Icons.Default.Description, contentDescription = null, tint = MaterialTheme.colorScheme.primary)
                Spacer(modifier = Modifier.width(8.dp))
                Text("📄 Monthly Business Report", fontWeight = FontWeight.Bold, fontSize = 18.sp)
            }
        },
        text = {
            Column(
                verticalArrangement = Arrangement.spacedBy(12.dp),
                modifier = Modifier.testTag("reports_modal_dialog")
            ) {
                Card(
                    shape = RoundedCornerShape(10.dp),
                    colors = CardDefaults.cardColors(containerColor = Color(0xFFF8FAFC)),
                    modifier = Modifier
                        .fillMaxWidth()
                        .border(1.dp, Color(0xFFE2E8F0), RoundedCornerShape(10.dp))
                ) {
                    Column(
                        modifier = Modifier.padding(12.dp),
                        verticalArrangement = Arrangement.spacedBy(4.dp)
                    ) {
                        Text("📊 Performance Summary:", fontWeight = FontWeight.Bold, style = MaterialTheme.typography.bodyMedium)
                        Text("Revenue: ${CurrencyFormatter.format(totalRevenue, currencySymbol)}")
                        Text("Production Cost: ${CurrencyFormatter.format(totalCost, currencySymbol)}")
                        Text("Net Profit: ${CurrencyFormatter.format(netProfit, currencySymbol)} (${CurrencyFormatter.formatPercent(margin)})", fontWeight = FontWeight.Bold, color = Color(0xFF047857))
                        Text("Total Orders Fulfilled: ${if (recordedOrders.isNotEmpty()) recordedOrders.size else 42}")
                    }
                }

                Text("📥 Export & Share Options:", fontWeight = FontWeight.Bold, style = MaterialTheme.typography.labelSmall)

                Button(
                    onClick = {
                        shareOnWhatsApp(reportText)
                    },
                    colors = ButtonDefaults.buttonColors(containerColor = Color(0xFF25D366)),
                    modifier = Modifier.fillMaxWidth().testTag("share_whatsapp_report_button"),
                    shape = RoundedCornerShape(8.dp)
                ) {
                    Icon(Icons.Default.Share, contentDescription = null, tint = Color.White)
                    Spacer(modifier = Modifier.width(8.dp))
                    Text("📱 Share Summary on WhatsApp", color = Color.White, fontWeight = FontWeight.Bold)
                }

                Row(horizontalArrangement = Arrangement.spacedBy(8.dp)) {
                    OutlinedButton(
                        onClick = {
                            Toast.makeText(context, "📄 Monthly Business Report PDF generated & saved!", Toast.LENGTH_SHORT).show()
                        },
                        modifier = Modifier.weight(1f).testTag("export_pdf_button"),
                        shape = RoundedCornerShape(8.dp)
                    ) {
                        Icon(Icons.Default.Download, contentDescription = null, modifier = Modifier.size(16.dp))
                        Spacer(modifier = Modifier.width(4.dp))
                        Text("Export PDF", fontSize = 12.sp)
                    }

                    OutlinedButton(
                        onClick = {
                            Toast.makeText(context, "📊 Monthly Business Data CSV exported successfully!", Toast.LENGTH_SHORT).show()
                        },
                        modifier = Modifier.weight(1f).testTag("export_csv_button"),
                        shape = RoundedCornerShape(8.dp)
                    ) {
                        Icon(Icons.Default.Download, contentDescription = null, modifier = Modifier.size(16.dp))
                        Spacer(modifier = Modifier.width(4.dp))
                        Text("Export CSV", fontSize = 12.sp)
                    }
                }
            }
        },
        confirmButton = {
            TextButton(onClick = onDismiss) {
                Text("Close")
            }
        }
    )
}
